rails-app/config/routes.rb
Rails.application.routes.draw do
  resources :audios
  resources :devices

  post '/api' => 'audios#ass_bot'

end

rails-app/app/models/audio.rb
# The model's class name is Audio.
class Audio < ActiveRecord::Base
  # Allows for store variable
  attr_accessor :store
  attr_writer :file_path, :url

  def path
    "public/audio/"
  end

  def url_path
    "http://192.168.1.121:3000/audio/"
  end

  def file_path
    if file
      return path + file
    else
      false
    end
  end

  def url
    if file
      return url_path + file
    else
      false
    end
  end

  # Display error if the user has not entered in a string.
  validates_presence_of :text, :message => "You can't say nothing."
end

rails-app/app/models/device.rb
class Device < ActiveRecord::Base
  @chromecasts = Device.where("device_type = ?", "Chromecast")
end

rails-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

end

rails-app/app/controllers/audios_controller.rb
require 'cgi' #Required for url_encode
include ESpeak #Required for audio functionality

class AudiosController < ApplicationController
  # GET /audios
  # GET /audios.json
  def index
    @audios = Audio.all
  end

  # GET /audios/1
  # GET /audios/1.json
  def show
    @audio = set_audio
  end

  # GET /audios/new
  def new
    @audio = Audio.new
  end

  # GET /audios/1/edit
  def edit
    @audio = set_audio
  end

  # POST /audios
  # POST /audios.json
  def create
    @audio = Audio.new
    @file = set_file_name(audio_params[:text])
    @url = @audio.url_path + @file # Creates the url to store
    @file_path = @audio.path + @file
    create_file = create_audio_file(audio_params[:text])
    say_text
    stream_audio

    respond_to do |format|
      if audio_params[:store] == "0" && @file_path.present? # If stream only
        delete_stream_file
        format.html { redirect_to new_audio_path, notice: 'Audio was sent for streaming.'}
        format.json { render :show, status: :created, location: @url }
      elsif audio_params[:store] == "1" && @file_path.present? # If stream and save
        @audio = Audio.new({ :text => audio_params[:text], :file => @file })
        if @audio.save
          format.html { redirect_to @audio, notice: 'Audio was successfully created.' }
          format.json { render :show, status: :created, location: @file }
        else
          format.html { render :new }
          format.json { render json: @audio.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end
    end
  end

  def ass_bot
    @audio = Audio.new
    @file = set_file_name(params[:text])
    @url = @audio.url_path + @file # Creates the url to store
    @file_path = @audio.path + @file
    create_file = create_audio_file(params[:text])
    said = say_text
    stream = stream_audio

    res = {
        :text => "Success!",
        :status => 200
    }
    render json: res
  end

  # PATCH/PUT /audios/1
  # PATCH/PUT /audios/1.json
  def update
    @file = set_file_name
    @audio = set_audio
    @delete_file = delete_audio_file
    @create_file = create_audio_file(audio_params[:text])
    respond_to do |format|
      if @audio.update({ :text => audio_params[:text], :file => @file })
        format.html { redirect_to @audio, notice: 'Audio was successfully created.' }
        format.json { render :show, status: :ok, location: @audio.url_path + @file }
      else
        format.html { render :edit }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audios/1
  # DELETE /audios/1.json
  def destroy
    @audio = set_audio
    @delete_file = delete_audio_file
    @audio.destroy
    respond_to do |format|
      format.html { redirect_to audios_url, notice: 'Audio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_name(text)
      text.downcase.tr(" ", "_").gsub(/[^0-9A-Za-z_]/, '') + ".mp3"
    end

    def set_audio
      Audio.find(params[:id])
    end

    # Create the audio files
    def create_audio_file(text)
      @speech = Speech.new(text)
      @speech.save(@file_path) # invokes espeak + lame
    end

    def delete_audio_file
      Thread.new{ `rm #{@audio.file_path}` }
    end

    def delete_stream_file
      Thread.new{ sleep(1.minute); `rm #{@file_path}`}
    end

    # Immediately speaks the text
    def say_text
      @speech.speak # invokes espeak
    end

    def stream_audio
      # Three threads for three chromecasts. final argument's ip needs to be changed to appropriate server machine's external ip.
      enc_url = CGI::escape(@url)
      # Chromecast Command
      # @err1 = Thread.new{ @cast1 = `castnow --address 10.0.190.83 #{@url}`}
      # @err2 = Thread.new{ @cast2 = `castnow --address 10.0.190.67 #{@url}`}
      # @err3 = Thread.new{ @cast3 = `castnow --address 10.0.190.63 #{@url}`}
      # Roku Command
      # @err4 = Thread.new{`curl -d '' 'http://<IP or HOSTNAME>:8060/launch/17846?streamformat=mp3&url=#{enc_url}'`}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audio_params
      if !params[:text]
        params.require(:audio).permit(:text, :store)
      else
        params.permit(:text)
      end
    end
end

rails-app/app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  def index
    @devices = Device.all
  end

  # GET /devices/1
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  def create
    puts device_params
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:location, :ip_host, :device_type)
    end
end

rails-app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-app/app/helpers/audios_helper.rb
module AudiosHelper
end

rails-app/app/helpers/devices_helper.rb
module DevicesHelper
end

rails-app/app/views/audios/_form.html.erb
<%= form_for(@audio) do |f| %>
  <div class = "input-container">
    <div class="field">
      <%= f.text_field :text, :placeholder => "Say something" %>
    </div>
    <%= button_tag(type: 'submit', class: "actions btn btn-primary") do %>
     <i class="glyphicon glyphicon-bullhorn"></i>
    <% end %>
  </div>
  <div class="checkbox">
    <% if @audio.id.present? # Only for the edit page %>
      <p><%= f.check_box :store, {checked: true, hidden: true} %></p>
    <% else # Shows on the new audio page %>
      <p><%= f.label 'Save?' %>
      <%= f.check_box :store, {checked: false} %></p>
    <% end %>
  </div>

  <% if @audio.errors.any? %>
    <div id="error_message">
      <% @audio.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    </div>
  <% end %>
<% end %>

rails-app/app/views/audios/edit.html.erb
<h1>Editing Audio</h1>

<%= render 'form' %>

<%= link_to 'Show', @audio %> |
<%= link_to 'Back', audios_path %>

rails-app/app/views/audios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Audios</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @audios.each do |audio| %>
      <tr>
        <td><%= audio.text %></td>
        <td><%= link_to 'Show', audio %></td>
        <td><%= link_to 'Edit', edit_audio_path(audio) %></td>
        <td><%= link_to 'Destroy', audio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Audio', new_audio_path %>

rails-app/app/views/audios/new.html.erb
<div class="wrapper">
  <h1 class="title">Ambient Sound System</h1>
  <div class="form">

    <%= render 'form' %>

    <!-- <%= link_to 'Back', audios_path %> -->
  </div>
</div>

rails-app/app/views/audios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @audio.text %>
</p>

<%= link_to 'Download', @audio.url %> |
<%= link_to 'Edit', edit_audio_path(@audio) %> |
<%= link_to 'Back', audios_path %>

rails-app/app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being registered:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :ip_host %><br>
    <%= f.text_field :ip_host %>
  </div>
  <div class="field">
    <%= f.label :device_type %><br>
    <%= f.text_field :device_type %>
  </div>
  <div class="actions">
    <%= f.submit :"Register Device" %>
  </div>
<% end %>

rails-app/app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

rails-app/app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registered Devices</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.location %></td>
        <td><%= device.ip_host %></td>
        <td><%= device.device_type %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Audio', new_device_path %>

rails-app/app/views/devices/new.html.erb
<div class="wrapper">
  <h1 class="title">Ambient Sound System</h1>
  <div class="form">
    <h2>New Audio</h2>

    <%= render 'form' %>

    <%= link_to 'Back', devices_path %>
  </div>
</div>

rails-app/app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @device.location %><br>
  <strong>IP or Hostname:</strong>
  <%= @device.ip_host %><br>
  <strong>Device Type:</strong>
  <%= @device.device_type %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

rails-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmbientSoundSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>